// SPDX-FileCopyrightText: 2023-present Lukas Neubert <lukas.neubert@proton.me>
// SPDX-License-Identifier: MPL-2.0

import { IDXS } from './types.js'

const LOKI_NOTE = 'Generated by Loki (https://github.com/loki-org/loki). Do not edit.'

class BaseGen {
	constructor(table) {
		this.table = table
		this.imports = new Set()
		this.headers = ''
		this.out = ''

		this.headers += this.comment_str(LOKI_NOTE)

		if (this.constructor === BaseGen) {
			throw new Error('Cannot instantiate BaseGen')
		}
	}

	gen(ast) {
		this.stmts(ast.body)

		for (const imp of this.imports) {
			this.import(imp)
		}

		return this.headers + '\n' + this.out
	}

	stmts(stmts) {
		for (const stmt of stmts) {
			this.stmt(stmt)
		}
	}

	stmt(stmt) {
		switch (stmt.kind) {
			case 'fn': {
				this.fn(stmt)
				break
			}
			default:
				throw new Error(stmt.kind)
		}
	}

	comment_str(text) {
		return `// ${text}\n`
	}

	import(imp) {
		throw new Error('Not implemented')
	}

	fn(fn) {
		throw new Error('Not implemented')
	}

	params(params) {
		throw new Error('Not implemented')
	}

	type(t) {
		throw new Error('Not implemented')
	}

	write(s) {
		this.out += s
	}

	writeln(s) {
		this.out += s + '\n'
	}
}

class CGen extends BaseGen {
	import(imp) {
		this.headers += `#include <${imp}>\n`
	}

	fn(fn) {
		const ret_type = this.type(fn.return_type)
		this.write(`${ret_type} ${fn.name}(`)
		this.params(fn.params)
		this.writeln(') {')
		this.stmts(fn.body)
		this.writeln('}')
	}

	params(params) {
		const param_list = []
		for (const param of params) {
			param_list.push(`${this.type(param.type)} ${param.name}`)
		}
		this.write(param_list.join(', '))
	}

	type(t) {
		switch (t) {
			case IDXS.i32:
				return 'int'
			case IDXS.u8:
				this.imports.add('stdint.h')
				return 'uint8_t'
			default:
				break
		}
		return this.table.sym(t).name
	}
}

class TsGen extends BaseGen {
	fn(fn) {
		const ret_type = this.type(fn.return_type)
		this.write(`function ${fn.name}(`)
		this.params(fn.params)
		this.writeln(`): ${ret_type} {`)
		this.stmts(fn.body)
		this.writeln('}')
	}

	params(params) {
		const param_list = []
		for (const param of params) {
			param_list.push(`${param.name}: ${this.type(param.type)}`)
		}
		this.write(param_list.join(', '))
	}

	type(t) {
		switch (t) {
			case IDXS.i32:
			case IDXS.u8:
				return 'number'
			default:
				break
		}
		return this.table.sym(t).name
	}
}

export { CGen, TsGen }
