// SPDX-FileCopyrightText: 2024-present Lukas Neubert <lukas.neubert@proton.me>
// SPDX-License-Identifier: MPL-2.0

const LOKI_HEADER = ' Generated by Loki (https://github.com/loki-org/loki). Do not edit.\n'

class BaseGen {
	constructor() {
		if (this.constructor === BaseGen) {
			throw new Error('Cannot instantiate BaseGen')
		}

		this.headers_out = this.comment_str(LOKI_HEADER)
	}

	gen(ast) {
		return this.headers_out + '\n'
	}

	comment_str(text) {
		return `//${text}`
	}
}

async function load_backend(backend) {
	try {
		const obj = await import(`./backends/${backend}.js`)
		return new obj.Gen()
	} catch (e) {
		console.error(e)
		process.exit(1)
	}
}

async function gen(ast, backend) {
	const b = await load_backend(backend)
	return b.gen(ast)
}

export { gen, BaseGen }
